services:
  - type: web
    name: damask-shop
    plan: free
    env: node
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: damask-db
          property: connectionString

databases:
  - name: damask-db
    plan: free