
services:
  - type: web
    name: damask-shop
    plan: free
    env: node
    buildCommand: npm install && npm run build
    startCommand: NODE_ENV=production tsx server/index.ts
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: damask-db
          property: connectionString

databases:
  - name: damask-db
    plan: free
    ipAllowList: []
